### ISSUE TITLE
A feature request (though, not really a necessary one)

### ISSUE THREAD

**Issue by lambdasapple** [leonrode/leonro.de#1]
I was looking through your website and i noticed that you had quick jump buttons and the words first letters were coloured pink
![image](https://user-images.githubusercontent.com/86855332/202532503-6246d427-4b4d-45ce-b78c-9cc9f644c2dc.png)
(what i'm talking about)
and since I saw the first letters being coloured my instinct was to click on a key on my keyboard to jump to a section (for example to jump to contacts i would press <kbd>c</kbd>), but it sadly didn't work. I think it would be a cool addition if you added it :))

**Comment by leonrode** [comment]
Thanks for the great idea! Just implemented this in 239268457214e4a7979b570f8417b002f27274dd.
